### ISSUE TITLE
Drop git from gemspec?

### ISSUE THREAD

**Issue by utkarsh2102** [marcandre/backports#140]
https://github.com/marcandre/backports/blob/1b53c219709350a19eb5371314dd9856ca957ffd/backports.gemspec#L16

Hi,
This doesn't really help much, can we please drop `git` from gemspec?
We, in Debian, are using a patch to remove this usage to avoid an unnecessary dependency :)

**Comment by rubyFeedback** [comment]
This is an interesting comment and I concur with it insofar as I had, a few days ago, realized that the meson-builds of gtk, pango, atk etc... all wish to automatically download dependencies based on the availability of git. This screwed up my own build process, because I had been using (and compiling) my own versions, and did not give my ok to the meson build to download anything (no idea how to prevent this).

Sorry for this off-topic, but perhaps it is understandable too why I think that the suggestion raised by utkarsh2102 appears to make sense (to me), unless there is some reason to require of "git". I don't think there is, though, because as far as I know we can use ruby in a .gemspec file as-is.

**Comment by marcandre** [comment]
Interesting.

I will gladly modify this gemspec for this project.

This gemspec was created using `bundle gem ...`, so the best would be to check issues of `bundler` and create a request to change this; the vast majority of gems will be using this `git` command by default otherwise.

**Comment by marcandre** [comment]
Fixed and released
